# Generated by Django 6.0.7 on 2026-07-17 13:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contact_name', models.CharField(max_length=200)),
                ('position', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('linkedin', models.URLField(blank=True)),
                ('origin', models.CharField(choices=[('linkedin', 'LinkedIn'), ('apollo', 'Apollo'), ('site', 'Site'), ('manual', 'Manual')], default='manual', max_length=20)),
                ('status', models.CharField(choices=[('novo', 'Novo'), ('contatado', 'Contatado'), ('respondeu', 'Respondeu'), ('reuniao', 'Reunião'), ('proposta', 'Proposta'), ('ganho', 'Ganho'), ('perdido', 'Perdido')], default='novo', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('next_followup', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='companies.company')),
            ],
        ),
    ]
